// Mock data for Menu page
export const mockMenuDishes = [
  // Pizza (6+)
  {
    id: 1,
    name: "Pizza Margherita",
    price: 18.99,
    category: "Pizza",
    calories: 280,
    description: "Pizza cổ điển với cà chua, mozzarella và húng quế tươi",
    image: "/api/placeholder/300/200?text=Pizza+Margherita",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 2,
    name: "Pizza Pepperoni",
    price: 19.99,
    category: "Pizza",
    calories: 320,
    description: "Pepperoni cay nhẹ và phô mai tan chảy",
    image: "/api/placeholder/300/200?text=Pizza+Pepperoni",
    available: true,
    spicy: true,
    fatty: true,
    sweet: false,
  },
  {
    id: 3,
    name: "Pizza Quattro Formaggi",
    price: 21.99,
    category: "Pizza",
    calories: 340,
    description: "Bốn loại phô mai Ý tuyệt hảo",
    image: "/api/placeholder/300/200?text=Pizza+4+Cheese",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 4,
    name: "Pizza Prosciutto",
    price: 22.49,
    category: "Pizza",
    calories: 330,
    description: "Thịt nguội Ý prosciutto và rocket",
    image: "/api/placeholder/300/200?text=Pizza+Prosciutto",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 5,
    name: "Pizza Funghi",
    price: 18.49,
    category: "Pizza",
    calories: 290,
    description: "Nấm tươi và mozzarella",
    image: "/api/placeholder/300/200?text=Pizza+Funghi",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 6,
    name: "Pizza Diavola",
    price: 20.99,
    category: "Pizza",
    calories: 360,
    description: "Xúc xích cay và ớt chuông",
    image: "/api/placeholder/300/200?text=Pizza+Diavola",
    available: true,
    spicy: true,
    fatty: true,
    sweet: false,
  },

  // Pasta (6+)
  {
    id: 11,
    name: "Pasta Carbonara",
    price: 16.99,
    category: "Pasta",
    calories: 320,
    description: "Mì ống với sốt kem, thịt xông khói và phô mai parmesan",
    image: "/api/placeholder/300/200?text=Carbonara",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 12,
    name: "Pasta Bolognese",
    price: 17.49,
    category: "Pasta",
    calories: 300,
    description: "Sốt bò bằm cà chua truyền thống",
    image: "/api/placeholder/300/200?text=Bolognese",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 13,
    name: "Pasta Pesto",
    price: 16.49,
    category: "Pasta",
    calories: 280,
    description: "Húng quế, hạt thông, dầu ô liu và parmesan",
    image: "/api/placeholder/300/200?text=Pesto",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 14,
    name: "Pasta Alfredo",
    price: 16.99,
    category: "Pasta",
    calories: 340,
    description: "Kem béo và phô mai parmesan",
    image: "/api/placeholder/300/200?text=Alfredo",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 15,
    name: "Pasta Arrabbiata",
    price: 15.99,
    category: "Pasta",
    calories: 270,
    description: "Sốt cà chua cay với ớt đỏ",
    image: "/api/placeholder/300/200?text=Arrabbiata",
    available: true,
    spicy: true,
    fatty: false,
    sweet: false,
  },
  {
    id: 16,
    name: "Pasta Seafood",
    price: 22.99,
    category: "Pasta",
    calories: 310,
    description: "Hải sản tươi và tỏi thơm",
    image: "/api/placeholder/300/200?text=Seafood+Pasta",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },

  // Main Course (6+)
  {
    id: 21,
    name: "Grilled Salmon",
    price: 24.99,
    category: "Main Course",
    calories: 250,
    description: "Cá hồi nướng với rau củ tươi và sốt chanh",
    image: "/api/placeholder/300/200?text=Grilled+Salmon",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 22,
    name: "Ribeye Steak",
    price: 29.99,
    category: "Main Course",
    calories: 450,
    description: "Bò Mỹ ribeye nướng vừa tới",
    image: "/api/placeholder/300/200?text=Ribeye+Steak",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 23,
    name: "Chicken Parmesan",
    price: 19.99,
    category: "Main Course",
    calories: 380,
    description: "Gà chiên giòn phủ sốt cà và phô mai",
    image: "/api/placeholder/300/200?text=Chicken+Parmesan",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 24,
    name: "Lamb Chops",
    price: 31.99,
    category: "Main Course",
    calories: 420,
    description: "Sườn cừu nướng và sốt rosemary",
    image: "/api/placeholder/300/200?text=Lamb+Chops",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 25,
    name: "Roasted Duck",
    price: 27.99,
    category: "Main Course",
    calories: 400,
    description: "Vịt quay sốt cam kiểu Âu",
    image: "/api/placeholder/300/200?text=Roasted+Duck",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 26,
    name: "Grilled Chicken",
    price: 18.99,
    category: "Main Course",
    calories: 300,
    description: "Gà nướng da giòn với thảo mộc",
    image: "/api/placeholder/300/200?text=Grilled+Chicken",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },

  // Salad (6+)
  {
    id: 31,
    name: "Caesar Salad",
    price: 12.99,
    category: "Salad",
    calories: 180,
    description: "Salad rau xanh với sốt Caesar và phô mai parmesan",
    image: "/api/placeholder/300/200?text=Caesar+Salad",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 32,
    name: "Greek Salad",
    price: 11.99,
    category: "Salad",
    calories: 160,
    description: "Ô liu, feta, dưa leo và cà chua",
    image: "/api/placeholder/300/200?text=Greek+Salad",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 33,
    name: "Nicoise Salad",
    price: 13.49,
    category: "Salad",
    calories: 200,
    description: "Cá ngừ, trứng, đậu que và khoai tây",
    image: "/api/placeholder/300/200?text=Nicoise+Salad",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 34,
    name: "Caprese Salad",
    price: 12.49,
    category: "Salad",
    calories: 170,
    description: "Cà chua, mozzarella và húng quế",
    image: "/api/placeholder/300/200?text=Caprese",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 35,
    name: "Quinoa Salad",
    price: 12.99,
    category: "Salad",
    calories: 190,
    description: "Hạt diêm mạch, rau củ và chanh",
    image: "/api/placeholder/300/200?text=Quinoa+Salad",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 36,
    name: "Smoked Salmon Salad",
    price: 14.99,
    category: "Salad",
    calories: 210,
    description: "Cá hồi xông khói và rau trộn",
    image: "/api/placeholder/300/200?text=Smoked+Salmon+Salad",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },

  // Dessert (6+)
  {
    id: 41,
    name: "Tiramisu",
    price: 8.99,
    category: "Dessert",
    calories: 350,
    description: "Bánh tiramisu với cà phê và mascarpone",
    image: "/api/placeholder/300/200?text=Tiramisu",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 42,
    name: "Panna Cotta",
    price: 7.99,
    category: "Dessert",
    calories: 280,
    description: "Panna cotta vanilla sốt dâu",
    image: "/api/placeholder/300/200?text=Panna+Cotta",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 43,
    name: "Chocolate Lava Cake",
    price: 9.49,
    category: "Dessert",
    calories: 420,
    description: "Bánh socola lava chảy",
    image: "/api/placeholder/300/200?text=Lava+Cake",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 44,
    name: "Cheesecake",
    price: 8.49,
    category: "Dessert",
    calories: 390,
    description: "Bánh phô mai kiểu New York",
    image: "/api/placeholder/300/200?text=Cheesecake",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 45,
    name: "Creme Brulee",
    price: 8.99,
    category: "Dessert",
    calories: 360,
    description: "Kem trứng caramel giòn",
    image: "/api/placeholder/300/200?text=Creme+Brulee",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 46,
    name: "Affogato",
    price: 6.99,
    category: "Dessert",
    calories: 210,
    description: "Kem vanilla và espresso nóng",
    image: "/api/placeholder/300/200?text=Affogato",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
];

export const categories = [
  { id: "all", name: "Tất cả" },
  { id: "Pizza", name: "Pizza" },
  { id: "Pasta", name: "Pasta" },
  { id: "Main Course", name: "Món chính" },
  { id: "Salad", name: "Salad" },
  { id: "Dessert", name: "Tráng miệng" },
];

export const preferences = [
  { id: "spicy", name: "Cay", description: "Thích đồ cay" },
  { id: "fatty", name: "Béo", description: "Thích đồ béo" },
  { id: "sweet", name: "Ngọt", description: "Thích đồ ngọt" },
  { id: "salty", name: "Mặn", description: "Thích đồ mặn" },
  { id: "sour", name: "Chua", description: "Thích đồ chua" },
];

export const goals = [
  { id: "lose", name: "Giảm cân", description: "Muốn giảm cân" },
  { id: "maintain", name: "Giữ dáng", description: "Muốn duy trì cân nặng" },
  { id: "gain", name: "Tăng cân", description: "Muốn tăng cân" },
];
