// Mock data for Menu page
export const mockMenuDishes = [
  {
    id: 1,
    name: "Pizza Margherita",
    price: 18.99,
    category: "Pizza",
    calories: 280,
    description: "Pizza cổ điển với cà chua, mozzarella và húng quế tươi",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 2,
    name: "Pasta Carbonara",
    price: 16.99,
    category: "Pasta",
    calories: 320,
    description: "Mì ống với sốt kem, thịt xông khói và phô mai parmesan",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: false,
    fatty: true,
    sweet: false,
  },
  {
    id: 3,
    name: "Grilled Salmon",
    price: 24.99,
    category: "Main Course",
    calories: 250,
    description: "Cá hồi nướng với rau củ tươi và sốt chanh",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 4,
    name: "Caesar Salad",
    price: 12.99,
    category: "Salad",
    calories: 180,
    description: "Salad rau xanh với sốt Caesar và phô mai parmesan",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: false,
    fatty: false,
    sweet: false,
  },
  {
    id: 5,
    name: "Tiramisu",
    price: 8.99,
    category: "Dessert",
    calories: 350,
    description: "Bánh tiramisu truyền thống với cà phê và mascarpone",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: false,
    fatty: true,
    sweet: true,
  },
  {
    id: 6,
    name: "Spicy Thai Noodles",
    price: 15.99,
    category: "Pasta",
    calories: 290,
    description: "Mì Thái cay với rau củ và thịt gà",
    image: "/api/placeholder/300/200",
    available: true,
    spicy: true,
    fatty: false,
    sweet: false,
  },
];

export const categories = [
  { id: "all", name: "Tất cả" },
  { id: "Pizza", name: "Pizza" },
  { id: "Pasta", name: "Pasta" },
  { id: "Main Course", name: "Món chính" },
  { id: "Salad", name: "Salad" },
  { id: "Dessert", name: "Tráng miệng" },
];

export const preferences = [
  { id: "spicy", name: "Cay", description: "Thích đồ cay" },
  { id: "fatty", name: "Béo", description: "Thích đồ béo" },
  { id: "sweet", name: "Ngọt", description: "Thích đồ ngọt" },
  { id: "salty", name: "Mặn", description: "Thích đồ mặn" },
  { id: "sour", name: "Chua", description: "Thích đồ chua" },
];

export const goals = [
  { id: "lose", name: "Giảm cân", description: "Muốn giảm cân" },
  { id: "maintain", name: "Giữ dáng", description: "Muốn duy trì cân nặng" },
  { id: "gain", name: "Tăng cân", description: "Muốn tăng cân" },
];
